import React from 'react'
import { Button, Divider, Col, Row, Checkbox, Drawer, Input } from 'antd'
import IntervalOption from '../../IntervalOption'
import { PDFViewer } from '@react-pdf/renderer'

class PDFMenu extends React.Component {
  constructor(props) {
    super(props)
  }

  render() {
    const defaultHistoricalOptions = []

    return (
      <Drawer
        visible={this.props.visible}
        title="Export to PDF"
        onClose={this.props.handleCancel}
        width="44%"
        headerStyle={{
          backgroundColor: '#4E4E4E',
          WebkitTextFillColor: 'white',
        }}
        destroyOnClose={true}
      >
        <div className="header">
          <Row>
            <Col span={8}>
              <h2 id="csv-pdf-report-preview">Historical Data</h2>
            </Col>
            <div id="pdf-select-date">
              <IntervalOption updateDates={this.props.handlePDFTimeChanges} />
            </div>
          </Row>
        </div>

        <div className="content">
          <Checkbox.Group
            style={{ width: '100%' }}
            defaultValue={defaultHistoricalOptions}
            onChange={this.props.handlePDFHistoricalSelections}
          >
            <Row>
              <Col span={8}>
                <Checkbox
                  value="avgDisposalCombined"
                  style={{ fontSize: 'medium' }}
                >
                  Average Disposal Combined
                </Checkbox>
              </Col>
              <Col span={8}>
                <Checkbox
                  value="avgDisposalType"
                  style={{ fontSize: 'medium' }}
                >
                  Average Disposal by Type
                </Checkbox>
              </Col>
              <Col span={8}>
                <Checkbox
                  value="disposalPercent"
                  style={{ fontSize: 'medium' }}
                >
                  Disposal Percentage
                </Checkbox>
              </Col>
            </Row>
            <br />
            <Row>
              <Col span={8}>
                <Checkbox value="disposalTotal" style={{ fontSize: 'medium' }}>
                  Total Disposal
                </Checkbox>
              </Col>
              <Col span={8}>
                <Checkbox value="divergenceRate" style={{ fontSize: 'medium' }}>
                  Divergence Rate
                </Checkbox>
              </Col>
            </Row>
          </Checkbox.Group>
        </div>

        <Divider></Divider>

        <div>
          <Row>
            <Col>
              <h2 id="csv-pdf-report-preview">Generated By: </h2>
            </Col>
            <Row>
              <Col span={15}>
                <Input
                  size="large"
                  placeholder="Peter Anteater"
                  allowClear
                  onChange={this.props.handleNameChange}
                />
              </Col>
              {/*
                    <Button id="pdf-enter-name-button" key="submit" type="primary" size="large" onClick={this.props.updateNameChange}>
                        Enter
                    </Button>
                    */}
            </Row>
          </Row>
        </div>

        <Divider></Divider>

        <div className="header">
          <Col span={12}>
            <h2 id="csv-pdf-report-preview">Report Preview</h2>
          </Col>
          <div id="csv-pdf-download-report-button">
            <Button
              key="submit"
              type="primary"
              size="large"
              onClick={this.props.handleOk}
            >
              Generate Preview
            </Button>
          </div>
        </div>
        <div className="content">
          <PDFViewer
            style={{
              width: '95%',
              height: '900px',
              boxShadow: '0 0 11px rgba(0, 0, 0, 0.15)',
              marginTop: '85px',
              marginLeft: 'auto',
              marginRight: 'auto',
              display: 'block',
            }}
          >
            {this.props.makePDF()}
          </PDFViewer>
        </div>
      </Drawer>
    )
  }
}

export default PDFMenu
